"""YWTA Link v1の依存なしProtocol foundation。"""

from .authority import (
    AUTHORITY_ACCEPTED_FIELDS,
    AUTHORITY_ACCEPTED_SCHEMA,
    AUTHORITY_REJECTED_FIELDS,
    AUTHORITY_REJECTED_SCHEMA,
    AUTHORITY_REQUEST_FIELDS,
    AUTHORITY_REQUEST_SCHEMA,
    AuthorityHandoffAccepted,
    AuthorityHandoffRejected,
    AuthorityHandoffRequest,
    AuthorityHandoffTracker,
    AuthorityState,
    AuthorityValidationError,
    PendingHandoff,
)
from .adapter import (
    AdapterDispatch,
    AdapterDispatchError,
    DispatchErrorInfo,
    DispatchOverflowError,
    DispatchStatus,
    HandlerErrorInfo,
)
from .contract import NegotiationResult, SyncChannel, SyncContract
from .camera import CAMERA_FIELDS, CAMERA_SCHEMA, FILM_FIT_VALUES, GATE_FIT_VALUES, Camera, CameraValidationError
from .client import LinkClient, LinkClientError
from .entity_ref import (
    ENTITY_REFERENCE_FIELDS,
    ENTITY_REFERENCE_SCHEMA,
    EntityReference,
    EntityReferenceValidationError,
)
from .envelope import Envelope, decode_envelope, encode_envelope
from .frame import Frame, FrameError, FrameLimits, decode_frame, encode_frame, read_frame, write_frame
from .presence import (
    PEER_HELLO_SCHEMA,
    PRESENCE_MAX_CAPABILITIES,
    PRESENCE_MAX_CAPABILITY_LENGTH,
    PRESENCE_MAX_PROTOCOL_VERSION,
    PRESENCE_MAX_PROTOCOL_VERSIONS,
    PRESENCE_MAX_STRING_LENGTH,
    PeerPresence,
    PresenceValidationError,
)
from .playback import (
    PLAYBACK_DIRECTION_VALUES,
    PLAYBACK_FIELDS,
    PLAYBACK_LOOP_MODE_VALUES,
    PLAYBACK_SCHEMA,
    PLAYBACK_STATE_VALUES,
    Playback,
    PlaybackEchoGuard,
    PlaybackValidationError,
)
from .session import ChannelRevisionTracker, SessionState, SyncSession
from .runtime import RuntimeError, RuntimeManifest, read_runtime_manifest, resolve_broker_executable
from .time import RATE_FIELDS, TIME_FIELDS, TIME_SCHEMA, RationalRate, Time, TimeValidationError
from .transform import (
    AXIS_VALUES,
    COORDINATE_SYSTEM_FIELDS,
    HANDEDNESS_VALUES,
    SPACE_VALUES,
    TRANSFORM_FIELDS,
    TRANSFORM_SCHEMA,
    UNIT_VALUES,
    CoordinateSystem,
    Transform,
    TransformValidationError,
)

__all__ = (
    "AdapterDispatch",
    "AdapterDispatchError",
    "DispatchErrorInfo",
    "AUTHORITY_ACCEPTED_FIELDS",
    "AUTHORITY_ACCEPTED_SCHEMA",
    "AUTHORITY_REJECTED_FIELDS",
    "AUTHORITY_REJECTED_SCHEMA",
    "AUTHORITY_REQUEST_FIELDS",
    "AUTHORITY_REQUEST_SCHEMA",
    "AuthorityHandoffAccepted",
    "AuthorityHandoffRejected",
    "AuthorityHandoffRequest",
    "AuthorityHandoffTracker",
    "AuthorityState",
    "AuthorityValidationError",
    "PendingHandoff",
    "ChannelRevisionTracker",
    "CAMERA_FIELDS",
    "CAMERA_SCHEMA",
    "FILM_FIT_VALUES",
    "GATE_FIT_VALUES",
    "Camera",
    "CameraValidationError",
    "ENTITY_REFERENCE_FIELDS",
    "ENTITY_REFERENCE_SCHEMA",
    "EntityReference",
    "EntityReferenceValidationError",
    "Envelope",
    "Frame",
    "FrameError",
    "FrameLimits",
    "LinkClient",
    "LinkClientError",
    "DispatchOverflowError",
    "DispatchStatus",
    "HandlerErrorInfo",
    "PEER_HELLO_SCHEMA",
    "PRESENCE_MAX_CAPABILITIES",
    "PRESENCE_MAX_CAPABILITY_LENGTH",
    "PRESENCE_MAX_PROTOCOL_VERSION",
    "PRESENCE_MAX_PROTOCOL_VERSIONS",
    "PRESENCE_MAX_STRING_LENGTH",
    "PeerPresence",
    "PresenceValidationError",
    "PLAYBACK_DIRECTION_VALUES",
    "PLAYBACK_FIELDS",
    "PLAYBACK_LOOP_MODE_VALUES",
    "PLAYBACK_SCHEMA",
    "PLAYBACK_STATE_VALUES",
    "Playback",
    "PlaybackEchoGuard",
    "PlaybackValidationError",
    "RATE_FIELDS",
    "RationalRate",
    "TIME_FIELDS",
    "TIME_SCHEMA",
    "Time",
    "TimeValidationError",
    "AXIS_VALUES",
    "COORDINATE_SYSTEM_FIELDS",
    "HANDEDNESS_VALUES",
    "SPACE_VALUES",
    "TRANSFORM_FIELDS",
    "TRANSFORM_SCHEMA",
    "UNIT_VALUES",
    "CoordinateSystem",
    "Transform",
    "TransformValidationError",
    "NegotiationResult",
    "SessionState",
    "SyncChannel",
    "SyncContract",
    "SyncSession",
    "RuntimeError",
    "RuntimeManifest",
    "decode_envelope",
    "decode_frame",
    "encode_envelope",
    "encode_frame",
    "read_frame",
    "read_runtime_manifest",
    "resolve_broker_executable",
    "write_frame",
)
