"""YWTA Link v1の依存なしProtocol foundation。"""

from .authority import (
    AUTHORITY_ACCEPTED_FIELDS,
    AUTHORITY_ACCEPTED_SCHEMA,
    AUTHORITY_REJECTED_FIELDS,
    AUTHORITY_REJECTED_SCHEMA,
    AUTHORITY_REQUEST_FIELDS,
    AUTHORITY_REQUEST_SCHEMA,
    AUTHORITY_SNAPSHOT_FIELDS,
    AUTHORITY_SNAPSHOT_REQUEST_FIELDS,
    AUTHORITY_SNAPSHOT_REQUEST_SCHEMA,
    AUTHORITY_SNAPSHOT_SCHEMA,
    AuthorityHandoffAccepted,
    AuthorityHandoffRejected,
    AuthorityHandoffRequest,
    AuthorityHandoffTracker,
    AuthoritySnapshot,
    AuthoritySnapshotRequest,
    AuthorityState,
    AuthorityValidationError,
    PendingHandoff,
)
from .authority_transport import AuthorityHandoffTransport, AuthorityTransportError, AuthorityTransportThreadError
from .adapter import (
    AdapterDispatch,
    AdapterDispatchError,
    DispatchErrorInfo,
    DispatchOverflowError,
    DispatchStatus,
    HandlerErrorInfo,
)
from .contract import NegotiationResult, SyncChannel, SyncContract
from .camera import CAMERA_FIELDS, CAMERA_SCHEMA, FILM_FIT_VALUES, GATE_FIT_VALUES, Camera, CameraValidationError
from .client import LinkClient, LinkClientError
from .entity_ref import (
    ENTITY_REFERENCE_FIELDS,
    ENTITY_REFERENCE_SCHEMA,
    EntityReference,
    EntityReferenceValidationError,
)
from .envelope import Envelope, decode_envelope, encode_envelope
from .frame import Frame, FrameError, FrameLimits, decode_frame, encode_frame, read_frame, write_frame
from .presence import (
    PEER_HELLO_SCHEMA,
    PRESENCE_MAX_CAPABILITIES,
    PRESENCE_MAX_CAPABILITY_LENGTH,
    PRESENCE_MAX_PROTOCOL_VERSION,
    PRESENCE_MAX_PROTOCOL_VERSIONS,
    PRESENCE_MAX_STRING_LENGTH,
    PeerPresence,
    PresenceValidationError,
)
from .playback import (
    PLAYBACK_DIRECTION_VALUES,
    PLAYBACK_FIELDS,
    PLAYBACK_LOOP_MODE_VALUES,
    PLAYBACK_SCHEMA,
    PLAYBACK_STATE_VALUES,
    Playback,
    PlaybackEchoGuard,
    PlaybackValidationError,
)
from .playback_host import (
    PlaybackHostEvent,
    PlaybackHostEventKind,
    PlaybackHostRange,
    PlaybackHostSnapshot,
    PlaybackHostValidationError,
)
from .playback_handoff import (
    PlaybackHandoffCoordinator,
    PlaybackHandoffError,
    PlaybackHandoffErrorInfo,
    PlaybackHandoffStatus,
    PlaybackHandoffThreadError,
)
from .playback_bootstrap import (
    PlaybackBootstrapConfig,
    PlaybackBootstrapError,
    bootstrap_playback_session,
)
from .playback_mapping import DEFAULT_REQUIRED_EXACT_FIELDS, PlaybackTimeMapper, PlaybackTimeMappingError
from .playback_controller import (
    AuthorityProvider,
    PlaybackController,
    PlaybackControllerError,
    PlaybackControllerErrorInfo,
    PlaybackControllerStatus,
    PlaybackControllerThreadError,
    PlaybackHostApply,
    PlaybackPublisher,
)
from .playback_transport import PlaybackTopicTransport, PlaybackTransportError, PlaybackTransportThreadError
from .playback_sync import (
    PlaybackSyncRuntime,
    PlaybackSyncRuntimeError,
    PlaybackSyncRuntimeErrorInfo,
    PlaybackSyncRuntimeStatus,
)
from .playback_session import PlaybackSession, PlaybackSessionConfig, PlaybackSessionError, compose_playback_session
from .session import ChannelRevisionTracker, SessionState, SyncSession
from .runtime import RuntimeError, RuntimeManifest, read_runtime_manifest, resolve_broker_executable
from .time import RATE_FIELDS, TIME_FIELDS, TIME_SCHEMA, RationalRate, Time, TimeValidationError
from .transform import (
    AXIS_VALUES,
    COORDINATE_SYSTEM_FIELDS,
    HANDEDNESS_VALUES,
    SPACE_VALUES,
    TRANSFORM_FIELDS,
    TRANSFORM_SCHEMA,
    UNIT_VALUES,
    CoordinateSystem,
    Transform,
    TransformValidationError,
)

__all__ = (
    "AdapterDispatch",
    "AdapterDispatchError",
    "DispatchErrorInfo",
    "AUTHORITY_ACCEPTED_FIELDS",
    "AUTHORITY_ACCEPTED_SCHEMA",
    "AUTHORITY_REJECTED_FIELDS",
    "AUTHORITY_REJECTED_SCHEMA",
    "AUTHORITY_REQUEST_FIELDS",
    "AUTHORITY_REQUEST_SCHEMA",
    "AUTHORITY_SNAPSHOT_FIELDS",
    "AUTHORITY_SNAPSHOT_REQUEST_FIELDS",
    "AUTHORITY_SNAPSHOT_REQUEST_SCHEMA",
    "AUTHORITY_SNAPSHOT_SCHEMA",
    "AuthorityHandoffAccepted",
    "AuthorityHandoffRejected",
    "AuthorityHandoffRequest",
    "AuthorityHandoffTracker",
    "AuthorityHandoffTransport",
    "AuthoritySnapshot",
    "AuthoritySnapshotRequest",
    "AuthorityTransportError",
    "AuthorityTransportThreadError",
    "AuthorityState",
    "AuthorityValidationError",
    "PendingHandoff",
    "ChannelRevisionTracker",
    "CAMERA_FIELDS",
    "CAMERA_SCHEMA",
    "FILM_FIT_VALUES",
    "GATE_FIT_VALUES",
    "Camera",
    "CameraValidationError",
    "ENTITY_REFERENCE_FIELDS",
    "ENTITY_REFERENCE_SCHEMA",
    "EntityReference",
    "EntityReferenceValidationError",
    "Envelope",
    "Frame",
    "FrameError",
    "FrameLimits",
    "LinkClient",
    "LinkClientError",
    "DispatchOverflowError",
    "DispatchStatus",
    "HandlerErrorInfo",
    "PEER_HELLO_SCHEMA",
    "PRESENCE_MAX_CAPABILITIES",
    "PRESENCE_MAX_CAPABILITY_LENGTH",
    "PRESENCE_MAX_PROTOCOL_VERSION",
    "PRESENCE_MAX_PROTOCOL_VERSIONS",
    "PRESENCE_MAX_STRING_LENGTH",
    "PeerPresence",
    "PresenceValidationError",
    "PLAYBACK_DIRECTION_VALUES",
    "PLAYBACK_FIELDS",
    "PLAYBACK_LOOP_MODE_VALUES",
    "PLAYBACK_SCHEMA",
    "PLAYBACK_STATE_VALUES",
    "Playback",
    "PlaybackEchoGuard",
    "PlaybackValidationError",
    "PlaybackHostEvent",
    "PlaybackHostEventKind",
    "PlaybackHostRange",
    "PlaybackHostSnapshot",
    "PlaybackHostValidationError",
    "PlaybackHandoffCoordinator",
    "PlaybackHandoffError",
    "PlaybackHandoffErrorInfo",
    "PlaybackHandoffStatus",
    "PlaybackHandoffThreadError",
    "PlaybackBootstrapConfig",
    "PlaybackBootstrapError",
    "bootstrap_playback_session",
    "DEFAULT_REQUIRED_EXACT_FIELDS",
    "PlaybackTimeMapper",
    "PlaybackTimeMappingError",
    "AuthorityProvider",
    "PlaybackController",
    "PlaybackControllerError",
    "PlaybackControllerErrorInfo",
    "PlaybackControllerStatus",
    "PlaybackControllerThreadError",
    "PlaybackHostApply",
    "PlaybackPublisher",
    "PlaybackTopicTransport",
    "PlaybackTransportError",
    "PlaybackTransportThreadError",
    "PlaybackSyncRuntime",
    "PlaybackSyncRuntimeError",
    "PlaybackSyncRuntimeErrorInfo",
    "PlaybackSyncRuntimeStatus",
    "PlaybackSession",
    "PlaybackSessionConfig",
    "PlaybackSessionError",
    "RATE_FIELDS",
    "RationalRate",
    "TIME_FIELDS",
    "TIME_SCHEMA",
    "Time",
    "TimeValidationError",
    "AXIS_VALUES",
    "COORDINATE_SYSTEM_FIELDS",
    "HANDEDNESS_VALUES",
    "SPACE_VALUES",
    "TRANSFORM_FIELDS",
    "TRANSFORM_SCHEMA",
    "UNIT_VALUES",
    "CoordinateSystem",
    "Transform",
    "TransformValidationError",
    "NegotiationResult",
    "SessionState",
    "SyncChannel",
    "SyncContract",
    "SyncSession",
    "RuntimeError",
    "RuntimeManifest",
    "decode_envelope",
    "decode_frame",
    "encode_envelope",
    "encode_frame",
    "read_frame",
    "read_runtime_manifest",
    "resolve_broker_executable",
    "write_frame",
    "compose_playback_session",
)
